lsst-ts/ts_criopy

Dockerfile, bin/VMSlogger, docker.vmslogger.service, python/lsst/ts/cRIOpy/DurationParser.py, python/lsst/ts/cRIOpy/__init__.py, tests/test_durationParser.py
Adds files to run VMSlogger from systemd. Adds few new options to VMSlogger.
=> VMSlogger can be run from systemd

python/lsst/ts/cRIOpy/GUI/ApplicationControlWidget.py, python/lsst/ts/cRIOpy/GUI/SALStatusBar.py
- XML v11 changes
- Shows limit from configuration, XML v11
=> DM-34047: Shows configured low/high pressure values instead of hardcoded

bin/M1M3GUI, python/lsst/ts/cRIOpy/GUI/Application.py, python/lsst/ts/cRIOpy/GUI/CompressorsPageWidget.py, python/lsst/ts/cRIOpy/GUI/CustomLabels.py, python/lsst/ts/cRIOpy/GUI/SALComm.py, python/lsst/ts/cRIOpy/GUI/TimeChart.py, python/lsst/ts/cRIOpy/GUI/TimeDeltaLabel.py, python/lsst/ts/cRIOpy/GUI/VMSChartWidgets.py, python/lsst/ts/cRIOpy/GUI/__init__.py
=> Air Compressor widget

python/lsst/ts/cRIOpy/GUI/SAL/__init__.py, python/lsst/ts/cRIOpy/M1M3/ApplicationControlWidget.py, python/lsst/ts/cRIOpy/M1M3/__init__.py, python/lsst/ts/cRIOpy/M1M3GUI.py
- Moved ApplicationControlWidget into M1M3
- SlewWiget, setAirSlewFlag command
=> Buttons for setAirSlewFlag command

python/lsst/ts/cRIOpy/AirCompressor/CompressorsPageWidget.py, python/lsst/ts/cRIOpy/GUI/SAL/VersionWidget.py, python/lsst/ts/cRIOpy/GUI/SAL/__init__.py
- Add VersionWidget
- Shows simulation mode
=> VersionWidget - shows version data

python/lsst/ts/cRIOpy/GUI/AbstractChart.py, python/lsst/ts/cRIOpy/GUI/Histogram.py, python/lsst/ts/cRIOpy/GUI/TimeChart.py, python/lsst/ts/cRIOpy/GUI/__init__.py, python/lsst/ts/cRIOpy/M1M3/ForceActuatorHistogramPageWidget.py, python/lsst/ts/cRIOpy/M1M3/ForceActuatorWidget.py, python/lsst/ts/cRIOpy/M1M3/__init__.py, python/lsst/ts/cRIOpy/M1M3GUI.py
- Moved functions to AbstractChart
- Histogram, AbstractChart
- Dialog to change number of bins
- Number of bins is configurable
=> Add histogram page

python/lsst/ts/cRIOpy/GUI/ValueGrid.py, python/lsst/ts/cRIOpy/VMS/Bars.py, python/lsst/ts/cRIOpy/VMS/CSCPSDWidget.py, python/lsst/ts/cRIOpy/VMS/Cache.py, python/lsst/ts/cRIOpy/VMS/CacheTimeWidget.py, python/lsst/ts/cRIOpy/VMS/CacheWidget.py, python/lsst/ts/cRIOpy/VMS/PSDWidget.py, python/lsst/ts/cRIOpy/VMS/RawAccelerationWidget.py, python/lsst/ts/cRIOpy/VMS/TimeBoxChart.py, python/lsst/ts/cRIOpy/VMS/__init__.py, python/lsst/ts/cRIOpy/VMSGUI.py
Added CSC PSD Widget to display CSC calculated PSD.
Some optimalization work is needed - PSDWidget and CSCPSDWidget should share common ancestor
supporting PSD plots. That shall be done in next PR.
=> Add CSC PSD Widget

Dockerfile, docker.vmslogger.service, python/lsst/ts/cRIOpy/TimeCache.py, python/lsst/ts/cRIOpy/VMSlogger.py, tests/test_TimeCache.py
- Fixed VMSlogger service
- Dropped sample_time argument from newChunk
- Fixed Dockerfile
- Retrieve period/frequency from fpgaState event
- TimeCache.timestampIndex method
- Fix files rotation
=> Properly rotate files

bin/vms5plot
- Added vms5plot - tool to plot PSD and data from HDF 5
- Add --raw argument
=> vms5plot script

Jenkinsfile, python/lsst/ts/cRIOpy/GUI/CustomLabels.py, python/lsst/ts/cRIOpy/M1M3/HardpointsWidget.py
- Show proximity encoder values & warnings
- setTextColor method for UnitLabel
=> Shows low/high proximity warnings

python/lsst/ts/cRIOpy/GUI/SAL/TopicData.py, python/lsst/ts/cRIOpy/M1M3/ForceActuatorWidget.py
- Add new forceActuatorSettings fields
- Add FollowingError fields
- Add counter fields
- use private_sndStamp if timestamp isn't available
=> Following Error improvements

python/lsst/ts/cRIOpy/GUI/ActuatorsDisplay/MirrorWidget.py, python/lsst/ts/cRIOpy/GUI/ActuatorsDisplay/WaitingScale.py, python/lsst/ts/cRIOpy/GUI/SAL/ApplicationStatusWidget.py, python/lsst/ts/cRIOpy/GUI/SAL/TopicData.py, python/lsst/ts/cRIOpy/GUI/TimeChart.py, python/lsst/ts/cRIOpy/M1M3/ActuatorOverviewPageWidget.py, python/lsst/ts/cRIOpy/M1M3/ApplicationControlWidget.py, python/lsst/ts/cRIOpy/M1M3/ForceActuator/Topics.py
- forceActuatorState -> raisingLoweringInfo
- Add FA raising state
=> Add FA Raising State, change supported percentage field

python/lsst/ts/cRIOpy/GUI/CustomLabels.py, python/lsst/ts/cRIOpy/GUI/StatusBox.py, python/lsst/ts/cRIOpy/GUI/__init__.py, python/lsst/ts/cRIOpy/M1M3/ApplicationControlWidget.py, python/lsst/ts/cRIOpy/M1M3/BoosterValveWidget.py, python/lsst/ts/cRIOpy/M1M3/ForceActuator/Topics.py, python/lsst/ts/cRIOpy/M1M3/ForceBalanceSystemPageWidget.py, python/lsst/ts/cRIOpy/M1M3/HardpointTestPageWidget.py, python/lsst/ts/cRIOpy/M1M3/HardpointsWidget.py, python/lsst/ts/cRIOpy/M1M3/OverviewPageWidget.py, python/lsst/ts/cRIOpy/M1M3/__init__.py, python/lsst/ts/cRIOpy/M1M3GUI.py
- BoosterValveStatus, BoosterValveOpen/Close commands
- StatusBox widget, BoosterValveWidget
- Accelerometer data in Booster Valve widget
- Fix BoosterValve display
- Doc strings
=> Show booster valve operation

python/lsst/ts/cRIOpy/GUI/ArrayGrid.py, python/lsst/ts/cRIOpy/GUI/CustomLabels.py, python/lsst/ts/cRIOpy/GUI/SAL/ApplicationStatusWidget.py, python/lsst/ts/cRIOpy/GUI/SAL/ChartWidget.py, python/lsst/ts/cRIOpy/GUI/SAL/TimeDeltaLabel.py, python/lsst/ts/cRIOpy/GUI/SAL/__init__.py, python/lsst/ts/cRIOpy/GUI/TimeChart.py, python/lsst/ts/cRIOpy/GUI/__init__.py, python/lsst/ts/cRIOpy/M1M3/ActuatorOverviewPageWidget.py, python/lsst/ts/cRIOpy/M1M3/AirPageWidget.py, python/lsst/ts/cRIOpy/M1M3/BoosterValveWidget.py, python/lsst/ts/cRIOpy/M1M3/DCAccelerometerPageWidget.py, python/lsst/ts/cRIOpy/M1M3/ForceActuator/ValuePageWidget.py, python/lsst/ts/cRIOpy/M1M3/GyroPageWidget.py, python/lsst/ts/cRIOpy/M1M3/HardpointsWidget.py, python/lsst/ts/cRIOpy/M1M3/IMSPageWidget.py, python/lsst/ts/cRIOpy/M1M3/InclinometerPageWidget.py, python/lsst/ts/cRIOpy/M1M3/OverviewPageWidget.py, python/lsst/ts/cRIOpy/M1M3/PIDPageWidget.py
- Convert DCAccelerometerPageWidget to CustomLabels
- AirPageWidget updated
- PID, Gyro and IMS rewrite
- Fix HP report
=> Rewrite old EUIs Widgets to new style EUI

python/lsst/ts/cRIOpy/M1M3/ForceActuator/Topics.py
- Measured force limits are in mirror space
- Applied force limits display
=> Meaured limits are in mirror space

python/lsst/ts/cRIOpy/GUI/ActuatorsDisplay/ForceActuator.py, python/lsst/ts/cRIOpy/GUI/SAL/TopicWindow.py, python/lsst/ts/cRIOpy/M1M3GUI.py, python/lsst/ts/cRIOpy/M1M3TS/ThermalData.py
- Button to open window with widget
- More ILC details
=> Shows ILC data

python/lsst/ts/criopy/gui/StatusBox.py, python/lsst/ts/criopy/gui/sal/StateEnabled.py, python/lsst/ts/criopy/gui/sal/__init__.py, python/lsst/ts/criopy/m1m3/ApplicationControlWidget.py, tests/test_force_calculator.py
- test_force_actuator
- Proper Slew Flag button
=> DM-40031: slewFlag functionality

doc/version_history.rst, python/lsst/ts/criopy/LTGUI.py, python/lsst/ts/criopy/M1M3GUI.py, python/lsst/ts/criopy/gui/ArrayGrid.py, python/lsst/ts/criopy/gui/actuatorsdisplay/BumpTestScale.py, python/lsst/ts/criopy/gui/sal/ApplicationStatusWidget.py, python/lsst/ts/criopy/gui/sal/StateEnabled.py, python/lsst/ts/criopy/m1m3/ActuatorOverviewPageWidget.py, python/lsst/ts/criopy/m1m3/ApplicationControlWidget.py, python/lsst/ts/criopy/m1m3/BoosterValveWidget.py, python/lsst/ts/criopy/m1m3/ForceBalanceSystemPageWidget.py, python/lsst/ts/criopy/m1m3/HardpointTestPageWidget.py, python/lsst/ts/criopy/m1m3/HardpointsWidget.py, python/lsst/ts/criopy/m1m3/OffsetsWidget.py, python/lsst/ts/criopy/m1m3/OverviewPageWidget.py, python/lsst/ts/criopy/m1m3/SlewControllerPageWidget.py, python/lsst/ts/criopy/m1m3/__init__.py, python/lsst/ts/criopy/m1m3/force_actuator/BumpTestPageWidget.py, python/lsst/ts/criopy/m1m3/force_actuator/Enabled.py, python/lsst/ts/criopy/m1m3/force_grid.py
- SlewControllerPageWidget
- Updated doc strings.
=> DM-40480: Slew Controller widget, improved Booster Valve control

.github/workflows/changelog.yaml, .ts_pre_commit_config.yaml, doc/version-history.rst, python/lsst/ts/criopy/M1M3GUI.py, python/lsst/ts/criopy/m1m3/ApplicationControlWidget.py, python/lsst/ts/criopy/m1m3ts/M1M3TSCSCControlWidget.py
- Moved Panic button
- -> None (mypy fix)
- Pause/Resume raising/lowering buttons
=> DM-39576: buttons to pause and resume mirror raising and lowering

doc/version-history.rst, python/lsst/ts/criopy/gui/actuatorsdisplay/enum_scale.py, python/lsst/ts/criopy/gui/actuatorsdisplay/force_actuator_item.py, python/lsst/ts/criopy/gui/actuatorsdisplay/gauge_scale.py, python/lsst/ts/criopy/gui/sal/application.py, python/lsst/ts/criopy/gui/sal/splash_screen.py, python/lsst/ts/criopy/m1m3/force_calculator.py, python/lsst/ts/criopy/m1m3simgui.py
- Ignore comments in CSV, report filename with parser error
- Config directory can be specified as argument
=> Improvements of M1M3SIMGUI

doc/version-history.rst, python/lsst/ts/criopy/m1m3/acceleration_and_velocity_fitter.py, python/lsst/ts/criopy/m1m3/application_control_widget.py, python/lsst/ts/criopy/m1m3/force_calculator.py, python/lsst/ts/criopy/m1m3simgui.py
- Use new enums, add option to use accelerometers
- ForceTable - manages DataFrame with its comments
- Change logging, create float 0 arrays
- Fix Slew on/off disable/enable
=> Fit retrieved DC accelerometer data

conda/meta.yaml, doc/version-history.rst, python/lsst/ts/criopy/gui/actuatorsdisplay/force_actuator_item.py, python/lsst/ts/criopy/gui/custom_labels.py, python/lsst/ts/criopy/m1m3/application_control_widget.py, python/lsst/ts/criopy/m1m3/hardpoint_test_page_widget.py
=> Fix typos & setColor calls

doc/version-history.rst, python/lsst/ts/criopy/gui/__init__.py, python/lsst/ts/criopy/gui/array_grid.py, python/lsst/ts/criopy/gui/custom_labels.py, python/lsst/ts/criopy/gui/data_form_widget.py, python/lsst/ts/criopy/gui/formators.py, python/lsst/ts/criopy/gui/time_chart.py, python/lsst/ts/criopy/m1m3/actuator_overview_page_widget.py, python/lsst/ts/criopy/m1m3/direction_pad_widget.py, python/lsst/ts/criopy/m1m3/force_grid.py, python/lsst/ts/criopy/m1m3/gyro_page_widget.py, python/lsst/ts/criopy/m1m3/hardpoints_widget.py, python/lsst/ts/criopy/m1m3/lvdt_page_widget.py, python/lsst/ts/criopy/m1m3/offsets_widget.py, python/lsst/ts/criopy/m1m3/pid_page_widget.py
- Add HP forces to offset page, fixed bugs
- Improved labeling
- formators.Formator, custom_labels.FormatLabel
- Added docstrings.
=> DM-46365: display additional data in offseting widget

doc/version-history.rst, python/lsst/ts/criopy/gui/actuatorsdisplay/enum_scale.py, python/lsst/ts/criopy/gui/actuatorsdisplay/force_actuator_item.py, python/lsst/ts/criopy/gui/custom_labels.py, python/lsst/ts/criopy/gui/time_chart.py, python/lsst/ts/criopy/m1m3/force_actuator/graph_page_widget.py, python/lsst/ts/criopy/m1m3/force_actuator/value_page_widget.py, python/lsst/ts/criopy/m1m3/force_grid.py, python/lsst/ts/criopy/m1m3/offsets_widget.py
- **Fixed omission from last renaming**
- **Return value if it cannot be mapped**
- **Fixed labes in M1M3 Offset page**
- **Unit name in TimeChart**
- **Don't show value for disabled FA**
=> DM-47981: fixed M1M3 errors and small bugs

doc/version-history.rst, python/lsst/ts/criopy/m1m3ts/mixing_valve_widget.py
- **Call applySetpoint CSC command**
- **Enable/disable temperature target**
- **Added doc lines for thermal control.**
=> DM-47221: add applySetpoint control for M1M3 thermal module

doc/version-history.rst, python/lsst/ts/criopy/gui/actuatorsdisplay/force_actuator_item.py, python/lsst/ts/criopy/gui/actuatorsdisplay/mirror.py, python/lsst/ts/criopy/gui/actuatorsdisplay/mirror_view.py, python/lsst/ts/criopy/gui/actuatorsdisplay/mirror_widget.py, python/lsst/ts/criopy/gui/sal/topic_window.py, python/lsst/ts/criopy/m1m3/force_actuator/enabled.py, python/lsst/ts/criopy/m1m3/force_actuator/graph_page_widget.py, python/lsst/ts/criopy/m1m3/force_actuator/histogram_page_widget.py, python/lsst/ts/criopy/m1m3/force_actuator/update_window.py, python/lsst/ts/criopy/m1m3/force_actuator/value_page_widget.py, python/lsst/ts/criopy/m1m3/force_actuator/widget.py, python/lsst/ts/criopy/m1m3ts/thermal_value_page_widget.py
=> snake_case methods related to actuators displays

doc/version-history.rst, python/lsst/ts/criopy/gui/sal/application_status_widget.py, python/lsst/ts/criopy/gui/sal/sal_status_bar.py, python/lsst/ts/criopy/gui/sal/summary_state_label.py, python/lsst/ts/criopy/gui/sal/topic_data.py, python/lsst/ts/criopy/gui/sal/topic_window.py, python/lsst/ts/criopy/m1m3gui.py, python/lsst/ts/criopy/m1m3ts/mixing_valve_widget.py, python/lsst/ts/criopy/m1m3ts/thermal_data.py, python/lsst/ts/criopy/m1m3ts/thermal_value_page_widget.py
=> DM-49538: Split heater and glycol loop setpoints, shows FCU settings

doc/version-history.rst, python/lsst/ts/criopy/gui/array_grid.py, python/lsst/ts/criopy/m1m3/force_grid.py, python/lsst/ts/criopy/m1m3/slew_controller_page_widget.py
This is now shown in the Slew controller:
=> Warning in "Slew controller" that flags cannot be changed when slew flag is set.
